name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            binary_name: mysql-mcp-server
            asset_name: mysql-mcp-server-linux-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            binary_name: mysql-mcp-server
            asset_name: mysql-mcp-server-linux-arm64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            binary_name: mysql-mcp-server
            asset_name: mysql-mcp-server-darwin-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            binary_name: mysql-mcp-server
            asset_name: mysql-mcp-server-darwin-arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
            binary_name: mysql-mcp-server.exe
            asset_name: mysql-mcp-server-windows-amd64.exe

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags="-s -w -X main.Version=${{ github.ref_name }}" -o ${{ matrix.binary_name }}

      - name: Create archive
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            7z a -tzip ${{ matrix.asset_name }}.zip ${{ matrix.binary_name }} README.md LICENSE
          else
            tar czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.binary_name }} README.md LICENSE
          fi
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: |
            ${{ matrix.asset_name }}.tar.gz
            ${{ matrix.asset_name }}.zip
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts/ -name "*.tar.gz" -o -name "*.zip" | xargs -I {} cp {} release-assets/
          ls -la release-assets/

      - name: Generate checksums
        run: |
          cd release-assets
          sha256sum *.tar.gz *.zip > checksums.txt
          cat checksums.txt

      - name: Generate release notes
        id: release_notes
        run: |
          cat > release_notes.md << 'EOF'
          ## What's New in ${{ github.ref_name }}

          This release includes pre-built binaries for multiple platforms and architectures.

          ### Features
          - MySQL database integration via Model Context Protocol (MCP)
          - Query execution with multiple output formats (table, CSV, markdown, JSON)
          - Schema inspection and table listing
          - Query caching for improved performance
          - Cross-platform support

          ### Installation

          **Linux (amd64):**
          ```bash
          curl -L https://github.com/koh-yoshimoto/mysql-mcp-server/releases/download/${{ github.ref_name }}/mysql-mcp-server-linux-amd64.tar.gz | tar xz
          chmod +x mysql-mcp-server
          sudo mv mysql-mcp-server /usr/local/bin/
          ```

          **macOS (Apple Silicon):**
          ```bash
          curl -L https://github.com/koh-yoshimoto/mysql-mcp-server/releases/download/${{ github.ref_name }}/mysql-mcp-server-darwin-arm64.tar.gz | tar xz
          chmod +x mysql-mcp-server
          sudo mv mysql-mcp-server /usr/local/bin/
          ```

          **macOS (Intel):**
          ```bash
          curl -L https://github.com/koh-yoshimoto/mysql-mcp-server/releases/download/${{ github.ref_name }}/mysql-mcp-server-darwin-amd64.tar.gz | tar xz
          chmod +x mysql-mcp-server
          sudo mv mysql-mcp-server /usr/local/bin/
          ```

          **Windows:**
          Download the `.zip` file and extract `mysql-mcp-server.exe` to a directory in your PATH.

          ### Supported Platforms
          - Linux (amd64, arm64)
          - macOS (amd64, arm64)
          - Windows (amd64)

          ### Verification
          After installation, verify with:
          ```bash
          mysql-mcp-server --version
          ```

          ### Documentation
          See the [README](https://github.com/koh-yoshimoto/mysql-mcp-server/blob/main/README.md) for configuration and usage instructions.
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: release_notes.md
          files: |
            release-assets/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}